VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">=1.9.1"
 
# Install vagrant-disksize to allow resizing the vagrant box disk.
unless Vagrant.has_plugin?("vagrant-disksize")
  raise  Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
end
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder "../..", "/home/vagrant/magma"
  config.vm.define :cwag, primary: true do |cwag|
	cwag.vm.box = "generic/ubuntu2004"
	cwag.disksize.size = '50GB'
	cwag.vm.box_version = "4.0.2"
	cwag.vbguest.auto_update = false
	cwag.vm.hostname = "cwag-dev"
	#eth1 - RADIUS and L2GRE iface
	cwag.vm.network "public_network", bridge: "enxf8e43b08beef", ip: "172.16.0.3", nic_type: "82540EM"
	#eth2 - Uplink iface
        cwag.vm.network "public_network", bridge: "eno1", nic_type: "82540EM", auto_config: false
	#bridged network for orc8r
	cwag.vm.network "public_network", bridge: "eno1"
	config.vm.provision "shell",
	run: "always",
	inline: "ifconfig eth2 up"
	cwag.ssh.password = "vagrant"
	cwag.ssh.insert_key = true
	cwag.vm.provider "virtualbox" do |vb|
  	vb.name = "cwag-dev"
  	vb.linked_clone = true
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
  	vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
	end
  end
end

